/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import load from "./script/scene/load"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1280;
    static height:number=720;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="load.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/scene/load.ts",load);
    }
}
GameConfig.init();